### ISSUE TITLE
Add a CHANGELOG.md

### ISSUE THREAD

**Issue by koppor** [adr/adr-log#2]
Add a CHANGELOG.md in the format as described at http://keepachangelog.com/. 

Example: Raw: https://raw.githubusercontent.com/eclipse/winery/master/CHANGELOG.md; Rendered: https://github.com/eclipse/winery/blob/master/CHANGELOG.md

Long example: https://github.com/JabRef/jabref/blob/master/CHANGELOG.md

**Comment by lharzenetter** [comment]
Closed by #14
